services:
  - type: web
    name: telegram-bitrix-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BITRIX_WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000
      - key: WEBHOOK_SECRET
        sync: false
